### ISSUE TITLE
Remove confusing part

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/nextjs-quickstart#1]
@sumitsaurabh927 Very good [quick start guide](https://docs.novu.co/overview/quickstart/get-started-with-nextjs), I really like idea, I got many inspirations for my guide, but in my opinion there is unecessary or even confusing part:

```ts
const result = await novu.topics.create({ key, name });
res.status(201).json(CircularJSON.stringify({ result }));
```

I am talking about usage of `circular-json`. It's very confusing and actually is just done wrong. If I would be reader without knowledge how Novu SDK works under the hood, I would assume something is wrong with sdk if it requires downloading some [deprecated package from npm](https://www.npmjs.com/package/circular-json).

What should be done is:
```ts
const result = await novu.topics.create({ key, name });
res.status(201).json(result.data);
```
@unicodeveloper @sumitsaurabh927 
We want to return `result.data`. It contains exacly what we want and is parsable as json. 
Response on screenshot is too bloated. It conatins parsed [Axios](https://www.npmjs.com/package/axios) (http library for Node.js) result with HTTP headers, with Request  stuff etc. We should just return response JSON data from Novu,

@sumitsaurabh927 Don't forget to make new screenshot for each route after changes

![image](https://github.com/novuhq/nextjs-quickstart/assets/43048524/903c46a1-1492-4344-8426-5884018a3066)

**Comment by unicodeveloper** [comment]
@michaldziuba03 Thanks for the catch. Your point makes sense. I'll let @sumitsaurabh927 respond to why this was included. Maybe there's a particular reason to the inclusion? 

Then, we can update based on that.
